name: CI/CD - Web Mahasiswa

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Ambil kode dari repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Validasi file HTML agar tidak ada error sintaks
      - name: Validate HTML files
        uses: chabad360/html-proofer@v1.0
        with:
          directory: ./
          check_html: true

      # 3️⃣ Validasi file JavaScript (pastikan tidak error syntax)
      - name: Check JavaScript syntax
        run: |
          for file in *.js; do
            echo "Checking syntax for $file"
            node --check "$file"
          done

      # 4️⃣ Tampilkan pesan sukses
      - name: Report success
        run: echo "✅ Build and test completed successfully!"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()
    steps:
      # 5️⃣ Checkout lagi sebelum deploy
      - name: Checkout repository
        uses: actions/checkout@v4

      # 6️⃣ Deploy ke GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
